name: Build CI

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  buildCi:
    name: Build CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: yarn

      - name: Build Page
        run: yarn build

      - name: Push New Build
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.API_TOKEN_GITHUB }}
        with:
          source-directory: 'build'
          destination-github-username: 'DerTyp7214'
          destination-repository-name: 'dertyp7214.github.io'
          user-email: lengwenath1@gmail.com
          target-branch: main
