name: Update Server

on:
  push:
    branches: [ master ]
  workflow_dispatch:

jobs:
  updateServer:
    name: Update Server
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Dependencies
        run: yarn

      - name: Set env vars
        run: echo "SECRET_KEY={{ secrets.SECRET_KEY }}" >> $GITHUB_ENV

      - name: Update Server
        run: yarn run updateServer